/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

int main(int argc, char *argv[]) {

    [NSApplication sharedApplication];
    if ([NSBundle loadNibNamed:@"NSMine" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];
    exit(0);
}
